### ISSUE TITLE
请问你这热加载原理是什么？

### ISSUE THREAD

**Issue by leeboya** [alanchenchen/hotload-cli#1]
请问alan大佬 这个脚手架的原理是什么，我好方便阅读您的源码 学习，谢谢喏！

**Comment by alanchenchen** [comment]
我这个是仿着supervisor的效果写的，别的库原理我不知道是啥，不过我这个是用了node的fs里面watch实现的文件监听。然后加载是用了child_process调用命令行，其实后来我考虑使用cluster模块来管理可能更好一点。。。。。因为node的文档太简陋了，子进程什么时候结束通信这个判断，我是通过打印child_process实例一个个看的属性。。。。。无比蛋疼。

**Comment by leeboya** [comment]
好的，谢谢你了，最近刚接触node,你的代码有助于我的技能提升！
